CALL RegisterRoomBed(1, 1, 2);  -- 2 camas de tipo 1 en la habitación 1
CALL RegisterRoomBed(1, 2, 1);  -- 1 cama de tipo 2 en la habitación 1
CALL RegisterRoomBed(2, 1, 3);  -- 3 camas de tipo 1 en la habitación 2
CALL RegisterRoomBed(2, 3, 2);  -- 2 camas de tipo 3 en la habitación 2
CALL RegisterRoomBed(3, 2, 1);  -- 1 cama de tipo 2 en la habitación 3
CALL RegisterRoomBed(3, 4, 4);  -- 4 camas de tipo 4 en la habitación 3
CALL RegisterRoomBed(4, 1, 1);  -- 1 cama de tipo 1 en la habitación 4
CALL RegisterRoomBed(4, 3, 3);  -- 3 camas de tipo 3 en la habitación 4
CALL RegisterRoomBed(5, 2, 2);  -- 2 camas de tipo 2 en la habitación 5
CALL RegisterRoomBed(5, 5, 1);  -- 1 cama de tipo 5 en la habitación 5
CALL RegisterRoomBed(6, 3, 1);  -- 1 cama de tipo 3 en la habitación 6
CALL RegisterRoomBed(6, 4, 2);  -- 2 camas de tipo 4 en la habitación 6
CALL RegisterRoomBed(7, 1, 2);  -- 2 camas de tipo 1 en la habitación 7
CALL RegisterRoomBed(7, 2, 1);  -- 1 cama de tipo 2 en la habitación 7
CALL RegisterRoomBed(8, 1, 3);  -- 3 camas de tipo 1 en la habitación 8
CALL RegisterRoomBed(8, 3, 1);  -- 1 cama de tipo 3 en la habitación 8
CALL RegisterRoomBed(9, 2, 2);  -- 2 camas de tipo 2 en la habitación 9
CALL RegisterRoomBed(9, 4, 1);  -- 1 cama de tipo 4 en la habitación 9
CALL RegisterRoomBed(10, 1, 1); -- 1 cama de tipo 1 en la habitación 10
CALL RegisterRoomBed(10, 3, 2); -- 2 camas de tipo 3 en la habitación 10
CALL RegisterRoomBed(11, 2, 2); -- 2 camas de tipo 2 en la habitación 11
CALL RegisterRoomBed(12, 1, 3); -- 3 camas de tipo 1 en la habitación 12
CALL RegisterRoomBed(13, 4, 1); -- 1 cama de tipo 4 en la habitación 13
CALL RegisterRoomBed(14, 5, 2); -- 2 camas de tipo 5 en la habitación 14
CALL RegisterRoomBed(15, 3, 1); -- 1 cama de tipo 3 en la habitación 15
CALL RegisterRoomBed(16, 2, 3); -- 3 camas de tipo 2 en la habitación 16
CALL RegisterRoomBed(17, 1, 2); -- 2 camas de tipo 1 en la habitación 17
CALL RegisterRoomBed(18, 4, 1); -- 1 cama de tipo 4 en la habitación 18
CALL RegisterRoomBed(19, 5, 2); -- 2 camas de tipo 5 en la habitación 19