CALL RegisterClient(12345678, 'Goku', 'Son', 'M', 'goku.son@example.com', 'Kamehameha');
CALL RegisterClient(98987271, 'Roque', 'Rivas', 'M', 'junior.rivaset12d1@gmail.com', 'Nah bueno!');
CALL RegisterClient(23456789, 'Vegeta', 'Prince', 'M', 'vegeta.prince@example.com', 'SaiyanPride');
CALL RegisterClient(34567890, 'Bulma', 'Briefs', 'F', 'bulma.briefs@example.com', 'GeniusTech');
CALL RegisterClient(45678901, 'Piccolo', 'Nail', 'M', 'piccolo.nail@example.com', 'NamekWarrior');
CALL RegisterClient(56789012, 'Homer', 'Simpson', 'M', 'homer.simpson@example.com', 'Doh123');
CALL RegisterClient(67890123, 'Marge', 'Simpson', 'F', 'marge.simpson@example.com', 'BlueHair2024');
CALL RegisterClient(78901234, 'Bart', 'Simpson', 'M', 'bart.simpson@example.com', 'Prankster2024');
CALL RegisterClient(89012345, 'Lisa', 'Simpson', 'F', 'lisa.simpson@example.com', 'SmartKid2024');
CALL RegisterClient(90123456, 'Nelson', 'Muntz', 'M', 'nelson.muntz@example.com', 'BullyingIsWrong');
CALL RegisterClient(98765432, 'Goku', 'Black', 'M', 'goku.black@example.com', 'EvilSaiyan');
CALL RegisterClient(87654321, 'Krillin', 'Destructo', 'M', 'krillin.destructo@example.com', 'BestFriend2024');
CALL RegisterClient(76543210, 'Ash', 'Ketchum', 'M', 'ash.ketchum@example.com', 'PikachuLover');
CALL RegisterClient(65432109, 'Misty', 'Water', 'F', 'misty.water@example.com', 'WaterTrainer');
CALL RegisterClient(54321098, 'Brock', 'Rock', 'M', 'brock.rock@example.com', 'RockHard');
CALL RegisterClient(43210987, 'Hijitus', 'Nerd', 'M', 'hijitus.nerd@example.com', 'SuperHijo');
CALL RegisterClient(32109876, 'Pichón', 'Gonzalez', 'M', 'pichon.gonzalez@example.com', 'PichonPower');
CALL RegisterClient(21098765, 'Don Ramón', 'Del Chavo', 'M', 'don.ramon@example.com', 'Chespirito2024');
CALL RegisterClient(19876543, 'Superhombre', 'Hero', 'M', 'superhombre.hero@example.com', 'ManOfSteel');
CALL RegisterClient(28765432, 'Chiquititas', 'Grupo', 'F', 'chiquititas.grupo@example.com', 'Niños2024');
CALL RegisterClient(37654321, 'Bart', 'Simpson', 'M', 'bart.simpson2@example.com', 'Rogue2024');
CALL RegisterClient(46543210, 'Peter', 'Parker', 'M', 'spider.man@example.com', 'WebSlinger');
CALL RegisterClient(55432109, 'Scooby', 'Doo', 'M', 'scooby.doo@example.com', 'ScoobySnacks');
CALL RegisterClient(64321098, 'Shaggy', 'Rogers', 'M', 'shaggy.rogers@example.com', 'Zoinks2024');
CALL RegisterClient(73210987, 'Yoda', 'Master', 'M', 'yoda.master@example.com', 'DoOrDoNot');
CALL RegisterClient(82109876, 'Darth', 'Vader', 'M', 'darth.vader@example.com', 'JoinTheDarkSide');
CALL RegisterClient(91098765, 'Mickey', 'Mouse', 'M', 'mickey.mouse@example.com', 'MagicKingdom2024');
CALL RegisterClient(10987654, 'Donald', 'Duck', 'M', 'donald.duck@example.com', 'Quack2024');
CALL RegisterClient(12345670, 'Bugs', 'Bunny', 'M', 'bugs.bunny@example.com', 'WhatsUpDoc');
CALL RegisterClient(34567891, 'McLovin', '', 'M', 'mclovin.si.yo.soy.mclovin@example.com', 'asi es soy mclovin');
CALL RegisterClient(10000001, 'Óscar', 'Córdoba', 'M', 'oscar.cordoba@example.com', 'Password1');
CALL RegisterClient(10000002, 'Hugo', 'Ibarra', 'M', 'hugo.ibarra@example.com', 'Password2');
CALL RegisterClient(10000003, 'Jorge', 'Bermúdez', 'M', 'jorge.bermudez@example.com', 'Password3');
CALL RegisterClient(10000004, 'Walter', 'Samuel', 'M', 'walter.samuel@example.com', 'Password4');
CALL RegisterClient(10000005, 'Juan', 'Riquelme', 'M', 'juan.riquelme@example.com', 'Password5');
CALL RegisterClient(10000006, 'Marcelo', 'Delgado', 'M', 'marcelo.delgado@example.com', 'Password6');
CALL RegisterClient(10000007, 'Guillermo', 'Barros Schelotto', 'M', 'guillermo.schelotto@example.com', 'Password7');
CALL RegisterClient(10000008, 'Martín', 'Palermo', 'M', 'martin.palermo@example.com', 'Password8');
CALL RegisterClient(10000009, 'Sebastián', 'Battaglia', 'M', 'sebastian.battaglia@example.com', 'Password9');
CALL RegisterClient(10000010, 'Diego', 'Cagna', 'M', 'diego.cagna@example.com', 'Password10');
CALL RegisterClient(10000011, 'Luis', 'Duran', 'M', 'Luis.Duran@example.com', 'Password11');
