CALL RegisterRoom('CON', 10000.00, 'Habitación con garaje y vista al mar.');
CALL RegisterRoom('SIN', 7500.50, 'Habitación económica sin garaje.');
CALL RegisterRoom('CON', 12000.25, 'Habitación de lujo con garaje privado.');
CALL RegisterRoom('SIN', 6000.00, 'Habitación estándar sin garaje.');
CALL RegisterRoom('CON', 15000.75, 'Suite con garaje y jacuzzi.');
CALL RegisterRoom('SIN', 8000.00, 'Habitación doble sin garaje.');
CALL RegisterRoom('CON', 20000.00, 'Habitación familiar con garaje y cocina.');
CALL RegisterRoom('SIN', 9000.00, 'Habitación simple sin garaje.');
CALL RegisterRoom('CON', 11000.50, 'Habitación premium con garaje y terraza.');
CALL RegisterRoom('SIN', 7000.00, 'Habitación básica sin garaje.');
CALL RegisterRoom('CON', 13000.00, 'Habitación con garaje y servicio de limpieza.');
CALL RegisterRoom('SIN', 8500.00, 'Habitación con desayuno incluido sin garaje.');
CALL RegisterRoom('CON', 14000.00, 'Habitación con garaje y acceso a la piscina.');
CALL RegisterRoom('SIN', 9500.00, 'Habitación doble con aire acondicionado sin garaje.');
CALL RegisterRoom('CON', 16000.00, 'Suite con garaje y vista panorámica.');
CALL RegisterRoom('SIN', 7200.00, 'Habitación sencilla sin garaje.');
CALL RegisterRoom('CON', 12500.00, 'Habitación con garaje y balcón privado.');
CALL RegisterRoom('SIN', 8800.00, 'Habitación con Wi-Fi gratuito sin garaje.');
CALL RegisterRoom('CON', 11500.00, 'Habitación adaptada para personas con discapacidad con garaje.');
CALL RegisterRoom('SIN', 6500.00, 'Habitación de paso sin garaje.');
